### ISSUE TITLE
A couple of minor issues

### ISSUE THREAD

**Issue by pitsi** [luzeagithub/smartversion-shell-scripts#1]
I decided to use your scripts today to do some svf patching and I came accross these issues.
The system in question runs 32bit debian unstable with no gui and the user does NOT have sudo capabilities.

First and foremost, the installation script fails with this error
```
# ./install-smartversion 
error: SmartVersion is not compatible with your processor architecture.
```
This is because, on line 11, lscpu reports "i686" instead of "i386" that the script expects.
```
$ lscpu 
Architecture:                    i686
CPU op-mode(s):                  32-bit
...
```
So please change it to i686. Another way is to use uname -m to get the "bits" of the installed operating system. On a 64bit system it returns
```
$ uname -m
x86_64
```
and on a 32bit
```
$ uname -m
i686
```
To be honest, I have no idea how it would behave on an i586 machine :( 

Second, in the same file, sudo is not needed on line 32. The user MUST run it as a root to work, so the $EUID requested at the beginning is 0. However, this
```
# echo $EUID
0
```
is different than this
```
$ sudo echo $EUID
1000
```
and I don't know why. For reference, the command was run on my main system where the user is capable of sudo.

Third, although I assume you already know it, the scripts for extraction etc must be moved to the working folder everytime in order to work. This is not an issue on my installation, because I can just drop them in ~/bin and have this in my ~/.bashrc to make bash use that folder too as $PATH.
`PATH=$PATH:$HOME/bin/`
As a behavior, it is exacty what some windows apps do by putting their installation path inside the user's $PATH for easier access. But how would you do that on linux? Would you ask the user to create ~/bin and add stuff tou his ~/.bashrc?

**Comment by luzeagithub** [comment]
You can simply move the scripts to `/bin` (`/usr/bin`) and run them from anywhere. Should I add that information to the README?

**Comment by pitsi** [comment]
It's up to you. I can write some instructions about "my" way if you want. Keep in mind that the patch script will interfere with the built in patch command, so a rename to "patch_smv" or similar will be needed.

**Comment by pitsi** [comment]
The installation script now works as it should. Well done :)
```
# ./install-smartversion 
--2021-01-25 11:31:42--  https://www.smartversion.com/smartvs38_linux_x86.zip
Resolving www.smartversion.com (www.smartversion.com)... 144.217.225.1
Connecting to www.smartversion.com (www.smartversion.com)|144.217.225.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 567122 (554K) [application/zip]
Saving to: ‘smartvs38_linux_x86.zip’

smartvs38_linux_x86 100%[===================>] 553.83K   141KB/s    in 3.9s    

2021-01-25 11:31:48 (141 KB/s) - ‘smartvs38_linux_x86.zip’ saved [567122/567122]

Archive:  smartvs38_linux_x86.zip
  inflating: smv                     
success: Successfully installed SmartVersion executable to /usr/bin/smv.
```

**Comment by pitsi** [comment]
About the $EUID. A guru friend says that, inside a script, the variable will be switched to zero and it will be kept zero for as long as the script is executed. So I made this tiny script
```
$ cat test.sh
#!/bin/bash
echo $EUID
```
When I run it as a simple user, it returns the id of that user
```
$ bash test.sh 
1000
```
and it returns 0 when it is run as a root
```
# bash test.sh 
0
```
And it also returns 0 when it is run via sudo! To be honest, I did not expect that.
```
$ sudo bash test.sh 
0
```
So, you can keep the code that does the mv further down as it is, without sudo, and just mention what it needs to be done when it will be run by a user with and without sudo priviledges.
